/*
 * This source file was generated by the Gradle 'init' task
 */
package be.ses;

public class App {


    public static void main(String[] args) {
       System.out.println("Hello World!"); 
    }
}
